AllCops:
  Exclude:
    - 'gemfiles/**/*'
  TargetRubyVersion: 2.2
Bundler/OrderedGems:
  Include:
    - 'Appraisals'
Layout/IndentHeredoc:
  Enabled: false
Layout/SpaceBeforeComma:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Performance/StartWith:
  Enabled: false
Performance/StringReplacement:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MethodMissingSuper:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Layout/ClosingHeredocIndentation:
  Enabled: false
