mysql:
  image: "mysql:5.6"
  ports:
    - "13316:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
mysql57:
  image: "mysql:5.7"
  ports:
    - "13317:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
postgres:
  image: "postgres:9.5"
  ports:
    - "15442:5432"
  environment:
    POSTGRES_PASSWORD: password
